/*
 * WARNING: do not edit!
 * Generated by util/mkbuildinf.pl
 *
 * Copyright 2014-2025 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#define PLATFORM "platform: sgx-linux-x86_64"
#define DATE "built on: Sat Apr  4 16:24:15 2026 UTC"

/*
 * Generate compiler_flags as an array of individual characters. This is a
 * workaround for the situation where CFLAGS gets too long for a C90 string
 * literal
 */
static const char compiler_flags[] = {
    'c','o','m','p','i','l','e','r',':',' ','g','c','c',' ','-','f',
    'P','I','C',' ','-','p','t','h','r','e','a','d',' ','-','m','6',
    '4',' ','-','W','a',',','-','-','n','o','e','x','e','c','s','t',
    'a','c','k',' ','-','W','a','l','l',' ','-','O','3',' ','-','i',
    'n','c','l','u','d','e','/','h','o','m','e','/','a','l','o','c',
    'i','n','-','l','o','c','a','l','/','t','d','x','-','p','q','-',
    'a','t','t','e','s','t','a','t','i','o','n','/','c','o','n','f',
    'i','d','e','n','t','i','a','l','-','c','o','m','p','u','t','i',
    'n','g','.','t','e','e','.','d','c','a','p','-','p','q','/','Q',
    'u','o','t','e','V','e','r','i','f','i','c','a','t','i','o','n',
    '/','s','g','x','s','s','l','/','L','i','n','u','x','/','.','.',
    '/','o','p','e','n','s','s','l','_','s','o','u','r','c','e','/',
    'b','y','p','a','s','s','_','t','o','_','s','g','x','s','s','l',
    '.','h',' ','-','D','O','P','E','N','S','S','L','_','U','S','E',
    '_','N','O','D','E','L','E','T','E',' ','-','D','L','_','E','N',
    'D','I','A','N',' ','-','D','O','P','E','N','S','S','L','_','P',
    'I','C',' ','-','D','O','P','E','N','S','S','L','_','B','U','I',
    'L','D','I','N','G','_','O','P','E','N','S','S','L',' ','-','D',
    'N','D','E','B','U','G',' ','-','D','_','F','O','R','T','I','F',
    'Y','_','S','O','U','R','C','E','=','2',' ','-','D','G','E','T',
    'P','I','D','_','I','S','_','M','E','A','N','I','N','G','L','E',
    'S','S',' ','-','D','O','P','E','N','S','S','L','_','N','O','_',
    'P','O','S','I','X','_','I','O','\0'
};
